path: c:\Users\kerem\OneDrive\Masaüstü\Politechnika Warszawska\EARIN - Intro to Artificial Intelligence\ship-detection\yolo_branch\data #has to be absolute path, not relative path
train: train/images #can be relative path
val: val/images

names:
  0: boat  #boat class